version: '3.8'
services:
    sqlserver: 
        image: mcr.microsoft.com/mssql/server
        container_name: sqlserver
        environment:
            SA_PASSWORD: "Yahmed062"
            ACCEPT_EULA: "Y"
        ports:
        - "1433:1433"
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api
        depends_on:
            - sqlserver
        environment:
            ConnectionStrings__DefaultConnection: "Server=DESKTOP-20DG3E0\\MSSQLSERVER01;Database=AdventureWorks;User Id=sa;Password=Yahmed062;"
        ports:
            - "8080:80"